////////////////////////////////////////////////////////////////////////////////
//
// Filename: project4.v
// Author:   Danny Dutton
// Date:     May 7 2014
// Revision: 0
//
// Description:
// This is the top level module for ECE 3544 Project 4.
// Do not modify the module declarations or ports in this file.
// When synthesizing to the DE1-SoC, this file should be used with the provided
// Quartus project so that the FPGA pin assignments are made correctly.
//
// YOU MUST MAKE THE PIN ASSIGNMENTS FOR THE INPUTS AND OUTPUTS OF THI MODULE.
// FOLLOW THE INSTRUCTIONS THAT YOU USED IN PROJECT 3.
// CONSULT THE MANUAL FOR INFORMATION ON THE PIN LOCATIONS.
//
// Modified for use with the DE1-SoC

//==========================================================
//  This code is generated by Terasic System Builder
//==========================================================

// Do NOT modify the module declaration.
module project4(CLOCK_50, KEY, SW, HEX5, HEX4, HEX3, HEX2, HEX1, HEX0, LED);

//==========================================================
//  PORT declarations: Do NOT modify these declarations.
//==========================================================

// You must use this clock for the clock of all of your sequential hardware.

	input CLOCK_50;

// KEY[0] should be used as reset, active low.
// KEY[1] should be used to enter operation codes and operands.
// The KEY pushbuttons are 1 when not pressed and 0 when pressed.

	input[1:0] KEY;

// SW[2] controls the mode.
// SW [1:0] represents a coin input.

	input[2:0] SW;

// The hex display outputs drive the seven segment displays.
// The LED output drives the LEDs.
	
	output [0:6] HEX5, HEX4, HEX3, HEX2, HEX1, HEX0;
	output [7:0] LED;

// You should add your reg/wire/parameter declarations here.

	wire enable;
	wire[7:0] nickel_counter, dime_counter, quarter_counter;
	
//=======================================================
// Module instantiantons
//=======================================================
	
// This is an instantiation of the keypressed module from Project 3.	
	
	keypressed K1(.clock(CLOCK_50),.reset(KEY[0]),.enable_in(KEY[1]),.enable_out(enable));

// You should add your module instantions here.
	vendingmachine V1 (.clock(CLOCK_50), 
							.enable(enable), 
							.reset(KEY[0]),
							.coin(SW[1:0]), 
							.mode(SW[2]), 
							.quarter_counter(quarter_counter),
							.dime_counter(dime_counter),
							.nickel_counter(nickel_counter),
							.dimenickelLEDon(LED[3]),
							.dimeLEDon(LED[1]),
							.nickelLEDon(LED[0]),
							.vendLEDon(LED[2]));

	sevensegdecoder_always S0 (.digit(nickel_counter[3:0]),
										.drivers(HEX0));
										
	sevensegdecoder_always S1 (.digit(nickel_counter[7:4]),
										.drivers(HEX1));
										
	sevensegdecoder_always S2 (.digit(dime_counter[3:0]),
										.drivers(HEX2));
										
	sevensegdecoder_always S3 (.digit(dime_counter[7:4]),
										.drivers(HEX3));

	sevensegdecoder_always S4 (.digit(quarter_counter[3:0]),
										.drivers(HEX4));
										
	sevensegdecoder_always S5 (.digit(quarter_counter[7:4]),
										.drivers(HEX5));
					  
endmodule
